site_name: Sistema GLOTTY
site_description: Documentación técnica por Axolotl Solutions
site_author: Axolotl Solutions
site_url: https://isaacjonathansantosrojas22590359.github.io/glottypage/

nav:
  - Inicio: index.md
  - Evolución del Proyecto: evolucion.md
  - Sprints:
    - Sprint 1: 
      - Resumen: sprints/sprint-1/index.md
      - Autenticación: sprints/sprint-1/autenticacion.md
      - CRUD Profesores: sprints/sprint-1/crud-profesores.md
      - Modelo Coordinador: sprints/sprint-1/coordinador.md
      - Modelo Profesor: sprints/sprint-1/profesor.md
      - Modelo Usuario: sprints/sprint-1/usuario.md
    - Sprint 2:
      - Resumen: sprints/sprint-2/index.md
      - Gestión de Aulas: sprints/sprint-2/aulas.md
      - Controlador de Aulas: sprints/sprint-2/aulaController.md
      - Administración de Horarios: sprints/sprint-2/horarios.md
    - Sprint 3:
      - Resumen: sprints/sprint-3/index.md
      - Periodos Académicos: sprints/sprint-3/periodos.md
      - Preregistros: sprints/sprint-3/preregistros.md
      - Gestión de Grupos: sprints/sprint-3/grupos.md
    - Sprint 4:
      - Resumen: sprints/sprint-4/index.md
      - Reestructuración: sprints/sprint-4/reestructuracion.md
      - Modelos: sprints/sprint-4/modelos.md
    - Próximos Sprints: sprints/proximos-sprints.md
  - Equipo: equipo.md

theme:
  name: material
  palette:
    primary: deep purple
    accent: blue

markdown_extensions:
  - tables
  - attr_list
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.arithmatex
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences



plugins:
  - search
  - mermaid2