site_name: Sistema GLOTTY
site_description: Documentación técnica por Axolotl Solutions
site_author: Axolotl Solutions
repo_url: https://isaacjonathansantosrojas22590359.github.io/glottypage/
site_name: Sistema GLOTTY
site_description: Documentación técnica por Axolotl Solutions
site_author: Axolotl Solutions
site_url: https://isaacjonathansantosrojas22590359.github.io/glottypage/

nav:
  - Inicio: index.md
  - Sprint 1: 
    - Resumen: sprint-1/index.md
    - Autenticación: sprint-1/autenticacion.md
    - CRUD Profesores: sprint-1/crud-profesores.md
  - Equipo: equipo.md

theme:
  name: material
  palette:
    primary: deep purple
    accent: blue

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search